### ISSUE TITLE
Replace scraper with actual MAL API implementation

### ISSUE THREAD

**Issue by James-Garden** [James-Garden/random-anime-picker#38]
Instead of going to the fixed /load.json URL, use the actual MAL API.
The JSON page does not work for all user's lists.

As an added bonus, this will mean the we're no longer blatantly breaking MyAnimeList's TOS.

**Comment by Orakeshi** [comment]
`As an added bonus, this will mean the we're no longer blatantly breaking MyAnimeList's TOS.`

Haha not breaking TOS is always a good thing lol
